# Site settings
title: Justyn Jen
email: justyngourdin@gmail.com
descrription: A personal webpage for Justyn Gourdin. She shares ebooks, travel tips and you can hire her to build your blog and help you start your blog or online business.
baseurl: ""
url: "http://justynjen.com"
